# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Hosted VS2017'

steps:
- powershell: .\SourceCode\RunPester.ps1 -Verbose

  displayName: 'Build and Test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testRunner: 'NUnit'
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'PS_Win2016'
