# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- powershell: ./SourceCode/RunPester.ps1 -Verbose
  workingDirectory: '$(System.DefaultWorkingDirectory)'

  displayName: 'PowerShell Script'

- task: PublishTestResults@2
  displayName: 'Publish Test Results SourceCode/TestResult.xml'
  inputs:
    testResultsFiles: SourceCode/TestResult.xml
